---
# Performs symlink exchange
- stat: path={{ deploy_to }}/{{ deploy_name }}
  become: yes
  become_user: www
  register: st

- name: Change softlink to new release
  file: state=link path={{ deploy_to }}/{{ deploy_name }} src="{{ release_path.stdout }}/{{ project_version }}"
  become: yes
  become_user: www
  when: export_path is not defined


- name: Change softlink to specific_path
  file: state=link path={{ deploy_to }}/{{ deploy_name }} src="{{ release_path.stdout }}/{{ project_version }}/{{ export_path }}"
  become: yes
  become_user: www
  when: export_path is defined and export_path !=''

- name: execute shell command *after cmd*
  command: /bin/sh  {{ after_cmd }} chdir="{{ deploy_to }}/{{ deploy_name }}"
  become: yes
  when: after_cmd is defined and after_cmd != ''
